apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: question-db-data-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard-rwm
