apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-db
  labels:
    app: question-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: question-db
  template:
    metadata:
      labels:
        app: question-db
    spec:
      containers:
        - name: question-db
          image: mongodb/mongodb-community-server:4.4.20@sha256:1017784ad6042dc22b961690ee19b2a9bfd5d1c37f8cf4b7ab3f51f142200409
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: question-db-data
            - mountPath: /data/configdb
              name: question-configdb-data
      restartPolicy: Always
      volumes:
        - name: question-db-data
          persistentVolumeClaim:
            claimName: question-db-data
        - name: question-configdb-data
          persistentVolumeClaim:
            claimName: question-configdb-data
