apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: question-db
spec:
  members: 1
  type: ReplicaSet
  version: "6.0.5"
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
