apiVersion: v1
kind: Service
metadata:
  name: question-service
  labels:
    app: question-service
spec:
  selector:
    app: question-service
  type: ClusterIP
  ports:
    - name: qn-service
      port: 8002
      targetPort: 8002
