apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-db
  labels:
    app: question-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: question-db
  template:
    metadata:
      labels:
        app: question-db
    spec:
      containers:
      - image: mongodb/mongodb-community-server:6.0-ubi8
        name: question-db
        volumeMounts:
        - mountPath: /data/db
          name: question-db-data
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
          requests:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
      volumes:
      - name: question-db-data
        persistentVolumeClaim:
          claimName: question-db-data-claim
      restartPolicy: Always
