apiVersion: v1
kind: Service
metadata:
  name: question-db
  labels:
    app: question-db
spec:
  selector:
    app: question-db
  type: ClusterIP
  ports:
    - name: question-db
      port: 27017
      targetPort: 27017
