apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: question-db-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  volumeName: question-db-data
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: question-db-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/mongo