apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-db
  labels:
    app: question-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: question-db
  template:
    metadata:
      labels:
        app: question-db
    spec:
      containers:
        - name: question-db
          image: mongodb/mongodb-community-server:latest
          command:
            - "--bind_ip"
            - "0.0.0.0"
          ports:
            - name: question-db
              containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: question-db-data
            - mountPath: /data/configdb
              name: question-configdb-data
      restartPolicy: Always
      volumes:
        - name: question-db-data
          persistentVolumeClaim:
            claimName: question-db-data
        - name: question-configdb-data
          persistentVolumeClaim:
            claimName: question-configdb-data