apiVersion: v1
kind: Service
metadata:
  name: collab-service
  labels:
    app: collab-service
spec:
  selector:
    app: collab-service
  type: ClusterIP
  ports:
    - name: collab-service
      port: 8004
      targetPort: 8004
