apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  type: ClusterIP
  ports:
    - name: user-service
      port: 8001
      targetPort: 8001
