apiVersion: v1
kind: Service
metadata:
  name: user-db
  labels:
    app: user-db
spec:
  selector:
    app: user-db
  type: ClusterIP
  ports:
    - name: user-db
      port: 27017
      targetPort: 27017
